a32nx briefing:
  - docs/pilots-corner/a32nx-briefing/**/*

beginner guide:
  - docs/pilots-corner/beginner-guide/**/*

advanced guides:
  - docs/pilots-corner/advance-guides/**/*

feature guide:
  - docs/fbw-a32nx/feature-guides/**/*

support:
  - docs/fbw-a32nx/support/*

repo:
  - '*'