# Project Information
site_name: FlyByWire Simulations Guides
site_url: https://docs.flybywiresim.com
# repo allows for linking main repo to docs
# Uncomment to use
repo_url: https://github.com/flybywiresim/a32nx/
repo_name: flybywiresim/a32nx
edit_uri: "" #removes edit button and icon

# Navigation
# Section Containers are defined by `- Section Name:`
# These should have NO filename.md next to them
# Nestle all pages under neath sections as seen below:
nav:
 - Home: index.md
 - Installation Guide:
   - Downloads + Guide: installation-guide/guide.md
 - A32NX Information:
   - Limitations: a32nx-information/limitations.md
 - Donate: donate.md
 - FAQ: faq.md

# Configuration
theme:
  name: material
# Theme Overhaul configruation. Use with caution.
# Uncomment custom_dir requires additional setup.
  #custom_dir: overrides
  logo: assets/images/FBW-Square-White.png
  palette:
    scheme: slate
  features:
   - navigation.tabs
   - navigation.instant
   - toc.integrate
  favicon: assets/images/FBW-tail.png

# Styling Front-end
extra_css:
  - stylesheets/extra.css

# Extra Functions / Customizations
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FlyByWireSimulations/
      name: FlyByWire Simulations on Facebook

# Additional Markdown Extensions to use bundled icon sets
markdown_extensions:
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list
  - pymdownx.tabbed #content tabs
  - pymdownx.details # Additional features to admonition
  - pymdownx.emoji: #Allows emjoy style inline embeds for icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
